name: Android APK erstellen

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Android APK erstellen
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Java einrichten
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle einrichten
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Android APK bauen
        run: gradle assembleDebug

      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: AutoCheck-APK
          path: "**/build/outputs/apk/debug/*.apk"
